// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9HTUgHLKuESI-30zgMt056ySKPoRU5Oc',
    appId: '1:328610864028:web:351a37ce40e74812464659',
    messagingSenderId: '328610864028',
    projectId: 'hhtest-fb9b6',
    authDomain: 'hhtest-fb9b6.firebaseapp.com',
    storageBucket: 'hhtest-fb9b6.firebasestorage.app',
    measurementId: 'G-KD85PJJPNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD14h6O5u3oumCi8pSlVIeJlU2AiNRCPzU',
    appId: '1:328610864028:android:cb06f2394c78c4c6464659',
    messagingSenderId: '328610864028',
    projectId: 'hhtest-fb9b6',
    storageBucket: 'hhtest-fb9b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASmsZqteQ995qGQRvLfY94oyT5dYYHG48',
    appId: '1:328610864028:ios:5f5a9eedeab9a8f4464659',
    messagingSenderId: '328610864028',
    projectId: 'hhtest-fb9b6',
    storageBucket: 'hhtest-fb9b6.firebasestorage.app',
    iosBundleId: 'app.vercel.khanstudio.hhTest',
  );
}
